[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = [
    "cd backend/HospitalService/src/HospitalService.Api",
    "dotnet restore"
]

[phases.build]
cmds = [
    "cd backend/HospitalService/src/HospitalService.Api",
    "dotnet build --configuration Release --no-restore"
]

[phases.start]
cmd = "cd backend/HospitalService/src/HospitalService.Api && dotnet run --configuration Release --urls http://0.0.0.0:$PORT --no-build"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"
