# syntax=docker/dockerfile:1
ARG PROJECT
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG PROJECT
WORKDIR /src
COPY . .
RUN dotnet restore MedTourism.sln
RUN dotnet publish ${PROJECT} -c Release -o /out

FROM base AS final
WORKDIR /app
COPY --from=build /out .
ENTRYPOINT ["dotnet", "$(basename ${PROJECT} .csproj).dll"]
