-- Messaging Service SQL schema
CREATE SCHEMA msg AUTHORIZATION dbo;

CREATE TABLE msg.Messages (
  Id BIGINT IDENTITY(1,1) PRIMARY KEY,
  FromUserId BIGINT NOT NULL,
  ToUserId BIGINT NOT NULL,
  Text NVARCHAR(2000) NOT NULL,
  CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
