-- Payment schema (stub)
CREATE SCHEMA pay AUTHORIZATION dbo;

CREATE TABLE pay.Payments (
  Id BIGINT IDENTITY(1,1) PRIMARY KEY,
  UserId BIGINT NOT NULL,
  Amount DECIMAL(12,2) NOT NULL,
  Currency NVARCHAR(8) NOT NULL,
  Status NVARCHAR(32) NOT NULL,
  CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
